version: '3'
services:
  web:
    image: 'jacobjdchoi/chois'
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    ports:
      - '80:80'
    volumes:
      - ./dist:/usr/share/nginx/html:ro